---
- name: test
  debug:
    msg: "lol"

- name: install mariadb and python mysqldb module
  yum:
    name:
      - mariadb-server
      - MySQL-python
  become: yes

- name: start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

- name: create wordpress database user
  mysql_user:
    host: "localhost"
    user: "{{wp_database_user}}"
    password: "{{wp_database_password}}"
    priv: '*.*:ALL,GRANT'
  become: yes
  no_log: yes

- name: create database for wordpress
  mysql_db:
    name: "{{wp_database}}"
    state: present
  become: yes

