---
- hosts: labserver1
  vars:
    release_version: 7
    base_arch: x86_64
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"
  tasks:
    - name: update yum package manager
      yum:
        update_cache: yes

    - name: import role to enable epel
      import_role:
        name: geerlingguy.repo-epel

    - name: check for epel repo configuration
      stat: path={{ epel_repofile_path }}
      register: epel_repofile_result

    - name: install epel repo
      yum:
        name: "{{ epel_repo_url }}"
        state: present
      register: result
      until: 'result.rc == 0'
      retries: 5
      delay: 10
      when: not epel_repofile_result.stat.exists

    - name: import epel GPG key
      rpm_key:
        key: "{{ epel_repo_gpg_key_url }}"
        state: present
      when: not epel_repofile_result.stat.exists
      ignore_errors: "{{ ansible_check_mode }}"

    - name: make sure ufw is installed and upto date
      yum:
        name: ufw
        state: latest
        disablerepo: "epel_repo"
      become: yes
